FORMAT: 1A
HOST: https://frozen-scrubland-43678.herokuapp.com

# Resang Authentication API
Welcome to the Resang API, soon to be extended to the all the application API!

# Group Authentication

## GET /

+ Response 200 (text/plain)

        Welcome to Resang!

+ Response 404 (text/plain)

        404 Page Not Found!


## GET /users

+ Response 200 (application/json)

        [users]

+ Response 404 (text/plain)

        404 Page Not Found!


## POST /auth/register

+ Parameters
    + userName: `hp` (string, required) - The user name of a Resang user
    + passWord: `resang` (string, required) - The password of a Resang user

+ Request Register New User (application/json)

        { "userName" : "", "passWord" : "" }


+ Response 200 (application/json)

        {
          success: true,
          message: 'Enjoy your token!',
          data: {token: token, content: "helloworld"}
        }

+ Response 404 (application/json)

        {
          success: false,
          message: 'User already exists!',
          data: {token: "No token authorized!", content: "helloworld"}
        }


## POST /auth/login

+ Parameters
      + userName: `hp` (string, required) - The user name of a Resang user
      + passWord: `resang` (string, required) - The password of a Resang user

+ Request Authenticate And Login User (application/json)

        { "userName" : "", "passWord" : "" }


+ Response 200 (application/json)

        {
          success: true,
          message: 'Enjoy your token!',
          data: {token: token, content: "helloworld"}
        }

+ Response 404 (application/json)

        {
          success: false,
          message: 'Authentication failed. User not found.'
        }

+ Response 403 (application/json)

        {
          success: false,
          message: 'Authentication failed. Wrong password.'
        }

## GET /api

+ Request

    + Headers

            Authorization: YOUR_TOKEN_HERE

+ Response 200 (application/json)

          { message: 'Welcome to the RESANG API!' }

## GET /api/users

+ Request

    + Headers

            Authorization: YOUR_TOKEN_HERE

+ Response 200 (application/json)

          [users]

## Messages [/messages]

### POST
Create and Save a Message

+ Request

    + Body

            { "userName" : "", "message" : "" }

+ Response 200 (application/json)

        {
          success: true,
          message: 'Message saved successfully!'
        }

### GET
Retrieve All Messages

+ Response 200

        [
            {
            "_id": "58b62c798e13a617f4d25fb1",
            "userName": "heranp",
            "message": "Hello world!",
            "__v": 0,
            "timestamp": "2017-03-01T02:05:45.861Z"
            },
            {
            "_id": "58b62caf8e13a617f4d25fb2",
            "userName": "kyle",
            "message": "Hey! My name is Kyle!",
            "__v": 0,
            "timestamp": "2017-03-01T02:06:39.526Z"
            },
            {
            "_id": "58b62cbd8e13a617f4d25fb3",
            "userName": "Tej",
            "message": "Yo! Tej in the house!",
            "__v": 0,
            "timestamp": "2017-03-01T02:06:53.518Z"
            },
            {
            "_id": "58b62cce8e13a617f4d25fb4",
            "userName": "Paul",
            "message": "Paul Chun will destroy you at Computer Engineering!",
            "__v": 0,
            "timestamp": "2017-03-01T02:07:10.719Z"
            }
        ]

# Group Images

## POST /images

  + Parameters
      + userName : `hp` (string, required) - The userName of user posting the event
      + file : `file` (file, required) - The file to upload

+ Request

    + Body

            { "userName" : "",
              "file" : "" }

+ Response 200 (application/json)

        { error_code : 0,
          err_desc : null }

+ Response 400 (application/json)

        {  error_code : 1,
           err_desc : err }

## POST /api/event/search

  + Parameters
      + latitude : `10.10` (string, required) - The user's current latitude
      + longitude : `10.10` (string, required) - The user's current longitude

+ Request

    + Body

            {
              "latitude" : "",
              "longitude" : ""
            }

    + Headers

            Authorization: YOUR_TOKEN_HERE

+ Response 200

        [events]
